services:
  - type: web
    name: minecraft-report-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_TOKEN
      - key: ADMIN_ID
